---
sudo: required

services:
  - docker

language: bash

before_install:
  - docker info
  - make build
  - docker build -t test:local ./Test

script:
  - make test

# only push up tags
after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make release;
    fi
